"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "sectors",
      [
        {
          id: 9990,
           name: "Bumbogo",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9991,
           name: "Kinyinya",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9992,
           name: "Ndera",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9993,
           name: "Gisozi",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9994,
           name: "Nduba",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9995,
           name: "Jabana",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9996,
           name: "Rusororo",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9997,
           name: "Kimironko",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9998,
           name: "Gatsata",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9999,
           name: "Jali",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99910,
           name: "Remera",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99911,
           name: "Kacyiru",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99912,
           name: "Rutunga",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99913,
           name: "Gikomero",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99914,
           name: "Kimihurura",
           districtId: 9990,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99915,
           name: "Gahanga",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99916,
           name: "Gatenga",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99917,
           name: "Gikondo",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99918,
           name: "Kagarama",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99919,
           name: "Kanombe",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99920,
           name: "Kicukiro",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99921,
           name: "Kigarama",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99922,
           name: "Masaka",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99923,
           name: "Niboye",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99924,
           name: "Nyarugunga",
           districtId: 9991,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99925,
           name: "Gitega",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99926,
           name: "Kanyinya",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99927,
           name: "Kigali",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99928,
           name: "Kimisagara",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99929,
           name: "Mageragere",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99930,
           name: "Muhima",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99931,
           name: "Nyakabanda",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99932,
           name: "Nyamirambo",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99933,
           name: "Nyarugenge",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99934,
           name: "Rwezamenyo",
           districtId: 9992,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99935,
           name: "Gashora",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99936,
           name: "Juru",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99937,
           name: "Kamabuye",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99938,
           name: "Ntarama",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99939,
           name: "Mareba",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99940,
           name: "Mayange",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99941,
           name: "Musenyi",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99942,
           name: "Mwogo",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99943,
           name: "Ngeruka",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99944,
           name: "Nyamata",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99945,
           name: "Nyarugenge",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99946,
           name: "Rilima",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99947,
           name: "Ruhuha",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99948,
           name: "Rweru",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99949,
           name: "Shyara",
           districtId: 9993,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99950,
           name: "Gahini",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99951,
           name: "Kabare",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99952,
           name: "Kabarondo",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99953,
           name: "Mukarange",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99954,
           name: "Murama",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99955,
           name: "Murundi",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99956,
           name: "Mwiri",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99957,
           name: "Ndego",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99958,
           name: "Nyamirama",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99959,
           name: "Rukara",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99960,
           name: "Ruramira",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99961,
           name: "Rwinkwavu",
           districtId: 9995,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99962,
           name: "Rwimiyaga",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99963,
           name: "Karangazi",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99964,
           name: "Nyagatare",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99965,
           name: "Katabagemu",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99966,
           name: "Rukomo",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99967,
           name: "Tabagwe",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99968,
           name: "Musheli",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99969,
           name: "Gatunda",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99970,
           name: "Mimuli",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99971,
           name: "Karama",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99972,
           name: "Matimba",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99973,
           name: "Mukama",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99974,
           name: "Rwempasha",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99975,
           name: "Kiyombe",
           districtId: 9998,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99976,
           name: "Gasange",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99977,
           name: "Gatsibo",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99978,
           name: "Gitoki",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99979,
           name: "Kabarore",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99980,
           name: "Kageyo",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99981,
           name: "Kiramuruzi",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99982,
           name: "Kiziguro",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99983,
           name: "Muhura",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99984,
           name: "Murambi",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99985,
           name: "Ngarama",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99986,
           name: "Nyagihanga",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99987,
           name: "Remera",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99989,
           name: "Rugarama",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99990,
           name: "Rwimbogo",
           districtId: 9994,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99991,
           name: "Gashanda",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99992,
           name: "Jarama",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99993,
           name: "Karembo",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99994,
           name: "Kazo",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99995,
           name: "Kibungo",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99996,
           name: "Mugesera",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99997,
           name: "Murama",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99998,
           name: "Mutenderi",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 99999,
           name: "Remera",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10000,
           name: "Rukira",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10001,
           name: "Rukumberi",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10002,
           name: "Rurenge",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10003,
           name: "Sake",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10004,
           name: "Zaza",
           districtId: 9997,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10005,
           name: "Gahara",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10006,
           name: "Gatore",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10007,
           name: "Kigarama",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10008,
           name: "Kigina",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10009,
           name: "Kirehe",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10010,
           name: "Mahama",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10011,
           name: "Mpanga",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10012,
           name: "Musaza",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10013,
           name: "Mushikiri",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10014,
           name: "Nasho",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10015,
           name: "Nyamugari",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10016,
           name: "Nyarubuye",
           districtId: 9996,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10017,
           name: "Fumbwe",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10018,
           name: "Gahengeri",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10019,
           name: "Gishari",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10020,
           name: "Karenge",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10021,
           name: "Kigabiro",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10022,
           name: "Muhazi",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10023,
           name: "Munyaga",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10024,
           name: "Munyiginya",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10025,
           name: "Musha",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10026,
           name: "Muyumbu",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10027,
           name: "Mwulire",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10028,
           name: "Nyakariro",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10029,
           name: "Nzige",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10030,
           name: "Rubona",
           districtId: 9999,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10031,
           name: "Bungwe",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10032,
           name: "Butaro",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10033,
           name: "Cyanika",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10034,
           name: "Cyeru",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10035,
           name: "Gahunga",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10036,
           name: "Gatebe",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10037,
           name: "Gitovu",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10038,
           name: "Kagogo",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10039,
           name: "Kinoni",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10040,
           name: "Kinyababa",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10041,
           name: "Kivuye",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10042,
           name: "Nemba",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10043,
           name: "Rugarama",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10044,
           name: "Rugendabari",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10045,
           name: "Ruhunde",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10046,
           name: "Rusarabuge",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10047,
           name: "Rwerere",
           districtId: 99910,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10048,
           name: "Busengo",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10049,
           name: "Coko",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10050,
           name: "Cyabingo",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10051,
           name: "Gakenke",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10052,
           name: "Gashenyi",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10053,
           name: "Mugunga",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10054,
           name: "Janja",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10055,
           name: "Kamubuga",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10056,
           name: "Karambo",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10057,
           name: "Kivuruga",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10058,
           name: "Mataba",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10059,
           name: "Minazi",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10060,
           name: "Muhondo",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10061,
           name: "Muyongwe",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10062,
           name: "Muzo",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10063,
           name: "Nemba",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10064,
           name: "Ruli",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10065,
           name: "Rusasa",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10066,
           name: "Rushashi",
           districtId: 99911,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10067,
           name: "Base",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10068,
           name: "Burega",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10069,
           name: "Bushoki",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10070,
           name: "Buyoga",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10071,
           name: "Cyinzuzi",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10072,
           name: "Cyungo",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10073,
           name: "Kinihira",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10074,
           name: "Kisaro",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10075,
           name: "Masoro",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10076,
           name: "Mbogo",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10077,
           name: "Murambi",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10078,
           name: "Ngoma",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10079,
           name: "Ntarabana",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10080,
           name: "Rukozo",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10081,
           name: "Rusiga",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3000,
           name: "Shyorongi",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10082,
           name: "Tumba",
           districtId: 99914,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10083,
           name: "Bukure",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10084,
           name: "Bwisige",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10085,
           name: "Byumba",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10086,
           name: "Cyumba",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10087,
           name: "Giti",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10088,
           name: "Kaniga",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10089,
           name: "Manyagiro",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10090,
           name: "Miyove",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10091,
           name: "Kageyo",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10092,
           name: "Muko",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10093,
           name: "Mutete",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10094,
           name: "Nyamiyaga",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10095,
           name: "Nyankenke II",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10096,
           name: "Rubaya",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10097,
           name: "Rukomo",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10098,
           name: "Rushaki",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10099,
           name: "Rutare",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10100,
           name: "Ruvune",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10101,
           name: "Rwamiko",
           districtId: 99912,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10102,
           name: "Busogo",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10103,
           name: "Cyuve",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10104,
           name: "Gacaca",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10105,
           name: "Gashaki",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10106,
           name: "Gataraga",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10107,
           name: "Kinigi",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10108,
           name: "Muhoza",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10109,
           name: "Muko",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10110,
           name: "Musanze",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10111,
           name: "Nkotsi",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10112,
           name: "Nyange",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10113,
           name: "Remera",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10114,
           name: "Rwaza",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10115,
           name: "Shingiro",
           districtId: 99913,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10116,
           name: "Bwishyura",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10117,
           name: "Gishyita",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10118,
           name: "Gishari",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10119,
           name: "Gitesi",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10120,
           name: "Mubuga",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10121,
           name: "Murambi",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10122,
           name: "Murundi",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10123,
           name: "Mutuntu",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10124,
           name: "Rubengera",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10125,
           name: "Rugabano",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10126,
           name: "Ruganda",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10127,
           name: "Rwankuba",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10128,
           name: "Twumba",
           districtId: 99923,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10129,
           name: "Bwira",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10130,
           name: "Gatumba",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10131,
           name: "Hindiro",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10132,
           name: "Kabaya",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10133,
           name: "Kageyo",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10134,
           name: "Kavumu",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10135,
           name: "Matyazo",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10136,
           name: "Muhanda",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10137,
           name: "Muhororo",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10138,
           name: "Ndaro",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10139,
           name: "Ngororero",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10140,
           name: "Nyange",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10141,
           name: "Sovu",
           districtId: 99924,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10142,
           name: "Bigogwe",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10143,
           name: "Jenda",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10144,
           name: "Jomba",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10145,
           name: "Kabatwa",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10146,
           name: "Karago",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10147,
           name: "Kintobo",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10148,
           name: "Mukamira",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10149,
           name: "Muringa",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10150,
           name: "Rambura",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10151,
           name: "Rugera",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10152,
           name: "Rurembo",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10153,
           name: "Shyira",
           districtId: 99925,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10154,
           name: "Ruharambuga",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10155,
           name: "Bushekeri",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10156,
           name: "Bushenge",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10157,
           name: "Cyato",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10158,
           name: "Gihombo",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10159,
           name: "Kagano",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10160,
           name: "Kanjongo",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10161,
           name: "Karambi",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10162,
           name: "Karengera",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10163,
           name: "Kirimbi",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10164,
           name: "Macuba",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10165,
           name: "Nyabitekeri",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10166,
           name: "Mahembe",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10167,
           name: "Rangiro",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3001,
           name: "Shangi",
           districtId: 99926,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3002,
           name: "Bugeshi",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3003,
           name: "Busasamana",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3004,
           name: "Cyanzarwe",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3005,
           name: "Gisenyi",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3006,
           name: "Kanama",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3007,
           name: "Kanzenze",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3008,
           name: "Mudende",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3009,
           name: "Nyakiliba",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3010,
           name: "Nyamyumba",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3011,
           name: "Nyundo",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3030,
           name: "Rubavu",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3090,
           name: "Rugerero",
           districtId: 99927,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3013,
           name: "Bugarama",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3014,
           name: "Butare",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3015,
           name: "Bweyeye",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3016,
           name: "Gikundamvura",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3017,
           name: "Giheke",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3018,
           name: "Gihundwe",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3019,
           name: "Gitambi",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3020,
           name: "Kamembe",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3021,
           name: "Muganza",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3022,
           name: "Mururu",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3023,
           name: "Nkanka",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3024,
           name: "Nkombo",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3025,
           name: "Nkungu",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3026,
           name: "Nyakabuye",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3027,
           name: "Nyakarenzo",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3028,
           name: "Nzahaha",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3029,
           name: "Rwimbogo",
           districtId: 99928,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10169,
           name: "Boneza",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10170,
           name: "Gihango",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10171,
           name: "Kigeyo",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10172,
           name: "Manihira",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10173,
           name: "Mukura",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10174,
           name: "Murunda",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10175,
           name: "Musasa",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10176,
           name: "Mushonyi",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10177,
           name: "Mushubati",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10178,
           name: "Nyabirasi",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10179,
           name: "Ruhango",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10180,
           name: "Rusebeya",
           districtId: 99929,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10181,
           name: "Gikonko",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10182,
           name: "Gishubi",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10183,
           name: "Kansi",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10184,
           name: "Kibilizi",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10185,
           name: "Kigembe",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10186,
           name: "Mamba",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10187,
           name: "Muganza",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10188,
           name: "Mugombwa",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10189,
           name: "Mukindo",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10190,
           name: "Musha",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10191,
           name: "Ndora",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10192,
           name: "Nyanza",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10193,
           name: "Save",
           districtId: 99915,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10194,
           name: "Gishamvu",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10195,
           name: "Karama",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10196,
           name: "Kigoma",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10197,
           name: "Kinazi",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10198,
           name: "Maraba",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10199,
           name: "Mbazi",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10200,
           name: "Mukura",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10201,
           name: "Ngoma",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10202,
           name: "Huye",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10203,
           name: "Rusatira",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10204,
           name: "Rwaniro",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10205,
           name: "Simbi",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10206,
           name: "Tumba",
           districtId: 99916,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10207,
           name: "Gacurabwenge",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10208,
           name: "Karama",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10209,
           name: "Kayenzi",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10210,
           name: "Kayumbu",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10211,
           name: "Mugina",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10212,
           name: "Musambira",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10213,
           name: "Ngamba",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10214,
           name: "Nyamiyaga",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10215,
           name: "Nyarubaka",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10216,
           name: "Rugalika",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10217,
           name: "Rukoma",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10218,
           name: "Runda",
           districtId: 99917,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10219,
           name: "Muhanga",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10220,
           name: "Cyeza",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10221,
           name: "Kibangu",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10222,
           name: "Kiyumba",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10223,
           name: "Mushishiro",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10224,
           name: "Kabacuzi",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10225,
           name: "Nyabinoni",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10226,
           name: "Nyamabuye",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10227,
           name: "Nyarusange",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10228,
           name: "Rongi",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10229,
           name: "Rugendabari",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10230,
           name: "Shyogwe",
           districtId: 99918,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10252,
           name: "Buruhukiro",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10253,
           name: "Cyanika",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10254,
           name: "Gatare",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10255,
           name: "Kaduha",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10256,
           name: "Kamegeli",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10257,
           name: "Kibirizi",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10258,
           name: "Kibumbwe",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10259,
           name: "Kitabi",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10260,
           name: "Mbazi",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10261,
           name: "Mugano",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10262,
           name: "Musange",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10263,
           name: "Musebeya",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10264,
           name: "Mushubi",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10265,
           name: "Nkomane",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10266,
           name: "Gasaka",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10267,
           name: "Tare",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10268,
           name: "Uwinkingi",
           districtId: 99919,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10269,
           name: "Busasamana",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10270,
           name: "Busoro",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10271,
           name: "Cyabakamyi",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10272,
           name: "Kibirizi",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10273,
           name: "Kigoma",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10274,
           name: "Mukingo",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10275,
           name: "Muyira",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10276,
           name: "Ntyazo",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10277,
           name: "Nyagisozi",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10278,
           name: "Rwabicuma",
           districtId: 99920,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10231,
           name: "Cyahinda",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10232,
           name: "Busanze",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10233,
           name: "Mata",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10234,
           name: "Munini",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10235,
           name: "Kivu",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10236,
           name: "Ngera",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10237,
           name: "Ngoma",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10238,
           name: "Nyabimata",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10239,
           name: "Nyagisozi",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10240,
           name: "Muganza",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3091,
           name: "Ruheru",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10242,
           name: "Ruramba",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10243,
           name: "Rusenge",
           districtId: 99921,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10244,
           name: "Kinazi",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10245,
           name: "Byimana",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10246,
           name: "Mbuye",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10247,
           name: "Ruhango",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10248,
           name: "Mwendo",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10249,
           name: "Kinihira",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10250,
           name: "Ntongwe",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10251,
           name: "Kabagari",
           districtId: 99922,
          active:true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },

      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("sectors", null, {});
  },
};
